/**
 * SoleVault - Backend Server
 * Auto-generated by Module Library Assembler
 * 
 * Run: npm install && npm run dev
 */

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();

// Trust proxy (required for Railway/Heroku/etc behind load balancer)
app.set('trust proxy', 1);

// ============================================
// MIDDLEWARE
// ============================================

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: true, credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// ============================================
// MODULE ROUTES (Auto-Wired)
// ============================================

const authRoutes = require('./modules/auth/routes/auth.js');
const stripe_paymentsRoutes = require('./modules/stripe-payments/routes/stripe.js');
const paymentsRoutes = require('./modules/payments/routes/payments.js');
const inventoryRoutes = require('./modules/inventory/routes/inventory.js');
const marketplaceRoutes = require('./modules/marketplace/routes/marketplace.js');
const vendor_systemRoutes = require('./modules/vendor-system/routes/vendor-sales.js');
const transfersRoutes = require('./modules/transfers/routes/transfer.js');
const ai_scannerRoutes = require('./modules/ai-scanner/routes/scanner.js');
const collectionsRoutes = require('./modules/collections/routes/collections.js');
const ebay_integrationRoutes = require('./modules/ebay-integration/routes/ebay-auth.js');
const nfc_tagsRoutes = require('./modules/nfc-tags/routes/nfc.js');
const showcaseRoutes = require('./modules/showcase/routes/showcase.js');
const admin_dashboardRoutes = require('./modules/admin-dashboard/routes/admin.js');
const analyticsRoutes = require('./modules/analytics/routes/metrics.js');
const admin_apiRoutes = require('./modules/admin-api/routes/analytics.js');

// Register routes
app.use('/api/auth', authRoutes);
app.use('/api/payments', stripe_paymentsRoutes);
app.use('/api/billing', paymentsRoutes);
app.use('/api/inventory', inventoryRoutes);
app.use('/api/marketplace', marketplaceRoutes);
app.use('/api/vendors', vendor_systemRoutes);
app.use('/api/transfers', transfersRoutes);
app.use('/api/scanner', ai_scannerRoutes);
app.use('/api/collections', collectionsRoutes);
app.use('/api/ebay', ebay_integrationRoutes);
app.use('/api/nfc', nfc_tagsRoutes);
app.use('/api/showcase', showcaseRoutes);
app.use('/api/admin', admin_dashboardRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/admin-api', admin_apiRoutes); // Changed from /api/admin to avoid conflict

// ============================================
// BRAIN & HEALTH ROUTES (Admin System)
// ============================================

const brainRoutes = require('./routes/brain');
const healthRoutes = require('./routes/health');

app.use('/api/brain', brainRoutes);
app.use('/api/health', healthRoutes);

// Quick health check (legacy)
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    project: 'SoleVault',
    timestamp: new Date().toISOString(),
    modules: 15
  });
});

// ============================================
// ERROR HANDLING
// ============================================

app.use((err, req, res, next) => {
  console.error('Error:', err.message);
  res.status(err.status || 500).json({
    error: err.message || 'Internal server error'
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.path });
});

// ============================================
// START SERVER
// ============================================

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log('');
  console.log('🚀 SoleVault backend running on port ' + PORT);
  console.log('   Health: http://localhost:' + PORT + '/health');
  console.log('   API:    http://localhost:' + PORT + '/api');
  console.log('');
  console.log('📦 Loaded modules (15):');
  console.log('   ✅ auth');
  console.log('   ✅ stripe-payments');
  console.log('   ✅ payments');
  console.log('   ✅ inventory');
  console.log('   ✅ marketplace');
  console.log('   ✅ vendor-system');
  console.log('   ✅ transfers');
  console.log('   ✅ ai-scanner');
  console.log('   ✅ collections');
  console.log('   ✅ ebay-integration');
  console.log('   ✅ nfc-tags');
  console.log('   ✅ showcase');
  console.log('   ✅ admin-dashboard');
  console.log('   ✅ analytics');
  console.log('   ✅ admin-api');
});

module.exports = app;
